# ekf.yaml - EKF 설정 파일

ekf_filter_node:
  ros__parameters:

    frequency: 15.0
    sensor_timeout: 0.5

    # 프레임 설정
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # 퍼블리시 설정
    publish_tf: true
    publish_acceleration: false

    # 입력 오도메트리 센서 설정
    odom0: odom_fwd
    odom0_config: [false, false, false,   # x, y, z
                   false, false, false, # roll, pitch, yaw
                   true, false, false,   # vx, vy, vz
                   false, false, true,  # vroll, vpitch, vyaw
                   false, false, false]   # accx, accy, accz

    odom0_differential: true
    odom0_relative: true

    odom1: odom_bwd
    odom1_config: [false, false, false,   # x, y, z
                   false, false, false, # roll, pitch, yaw
                   true, false, false,   # vx, vy, vz
                   false, false, true,  # vroll, vpitch, vyaw
                   false, false, false]   # accx, accy, accz

    odom1_differential: true
    odom1_relative: true


    # IMU 센서 설정
    imu0: imu_meas
    imu0_config: [false, false, false,   # x, y, z
                  false, false, false,   # roll, pitch, yaw
                  false, false, false,   # vx, vy, vz
                  false, false, true,    # vroll, vpitch, vyaw (yaw rate only)
                  false, false, false]   # accx, accy, accz

    imu0_differential: true
    imu0_relative: true


    # use_control: true
    use_control: false

    # The last issued control command will be used in prediction for this period. Defaults to 0.2.
    control_timeout: 0.2

    # Which velocities are being controlled. Order is vx, vy, vz, vroll, vpitch, vyaw.
    control_config: [true, false, false, false, false, true]

    # Places limits on how large the acceleration term will be. Should match your robot's kinematics.
    acceleration_limits: [1.5, 0.0, 0.0, 0.0, 0.0, 3.4]

    # Acceleration and deceleration limits are not always the same for robots.
    deceleration_limits: [1.5, 0.0, 0.0, 0.0, 0.0, 3.4]

    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0

    # 상태 초기화 옵션
    print_diagnostics: true
    debug: false
